name: "Run tests"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
